[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
axum = "0.6.20"
dotenvy = "0.15.7"
jsonrpsee-core = "0.20.0"
jsonrpsee-http-client = "0.20.0"
log = "0.4.20"
serde = "1.0.183"
serde_json = "1.0.104"
starknet = "0.7.0"
tokio = { version = "1.31.0", features = [ "full" ] }
tower-http = { version = "0.4.3", features = ["add-extension", "fs", "cors"] }
thiserror = "1.0.49"
dojo-world = { git = "https://github.com/dojoengine/dojo.git", tag = "v0.3.10", features = [ "manifest" ] }
url = "2.4.0"
